version: '3.9'

services:
  web:
    build: .
    command: hypercorn manager.asgi:app --log-file -
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env.prod

volumes:
  postgres_data: null
