# Generated by Django 3.2.10 on 2022-04-27 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20180403_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='found_date',
        ),
        migrations.AddField(
            model_name='company',
            name='created',
            field=models.DateTimeField(auto_now_add=True,
                                       default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
